version: '3.3'

services:
  api:
    container_name: api
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - 8001:8001
    command: yarn start:dev

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    # command: [--auth]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgrespw
      # POSTGRES_DB: postgres
    ports:
        - 5432:5432
    volumes:
      - ./db-data:/data/db